### ISSUE TITLE
Errors in the latest window version using script installer

### ISSUE THREAD

**Issue by jzarzour** [sireum/kekinian#6]
Hello, I used the window script installer provided on your website https://sireum.org/getting-started/, just wanted to point out that the commands to install the additional programs are in an install file and not a sirieum file (example: "%SIREUM_HOME%\bin\sireum\fmide.cmd" is wrong it's actually "%SIREUM_HOME%\bin\install\"). Moreover trying to install fmide on the latest versions seems not to be working as I get the error 

`The installable unit org.sireum.aadl.osate.feature.feature.group/1.2024.10301208.4e3e80ef has not been found.`

Older versions such as Oct 7 seem to work fine.

**Comment by robby-phd** [comment]
Thanks for reporting the issues. The website instructions have been fixed.

@jasonbelt Please take a look at the FMIDE issue.

**Comment by jasonbelt** [comment]
We updated the plugin versions the fmide script installs and also updated it to use OSATE 2.13 rather than 2.10.  To get the updates, run the [development build install scripts](https://sireum.org/getting-started/#latest-dev-bin) and then run the fmide install script.
